default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: postgres
  password: ''

development:
  <<: *default
  database: tasks_dev

test:
  <<: *default
  database: tasks_test

production:
  <<: *default
  database: tasks
